### ISSUE TITLE
The latest release published on npm is v0.0.4

### ISSUE THREAD

**Issue by stephane** [spences10/svead#149]
**Describe the bug**

I would expect to fetch the latest release v0.0.8 instead of v0.0.4 on `pnpm add -D svead`.

**To Reproduce**

`pnpm add -D svead`.

**Expected behavior**

Fetching latest Github release.

**Comment by spences10** [comment]
Hey @stephane thanks for stopping by 😊

The latest version is behind a canary flag, you can install it with `pid -D svead@canary` 

It's untested, as I'm testing it currently, there's no breaking changes, just a lot added to the API

**Comment by stephane** [comment]
OK I will test it and provide feedback.

**Comment by spences10** [comment]
Awesome! I haven't fully fleshed out the documentation looking at the README so there may be some parts in there you'll need to depend on the type completion for using the schema-org parts.

Let me know how you get on, I have v0.0.8 currently installed on a project byt need to implement it.

Maybe we could open up a discussion around use cases and where things don't quite work as expected?

I really appreciate the collaboration 🙏
